#
# Makefile for the drm device driver.  This driver provides support for the
# Direct Rendering Infrastructure (DRI) in XFree86 4.1.0 and higher.

obj-y := xilinx_vtc.o
obj-$(CONFIG_FB_XILINX_VDMA) += xilinx_vdmafb.o
